name: prspy
description: Mobile version of Project Reality PRSPY

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/http
  http: 0.13.5
  # https://pub.dev/packages/flag
  flag: 6.0.0
  # https://pub.dev/packages/marquee
  marquee: 2.2.3
  # https://pub.dev/packages/url_launcher
  url_launcher: 6.1.6
  # https://pub.dev/packages/package_info_plus
  package_info_plus: 2.0.0
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 2.0.15
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/dart_code_metrics
  dart_code_metrics: 4.21.1
  # https://pub.dev/packages/flutter_lints
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/ca/certificate.pem
    - assets/images/
    - assets/images/faction_flags/
    - assets/images/asset_icons/
    - assets/flags/